services:
  subscriber:
    build: .
    depends_on:
      db:
        condition: service_healthy # Wait until the 'db' service reports as healthy    
    ports:
      - 8082:8088
    environment:
      - DBHOST=db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - mysql_db_data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

volumes:
  mysql_db_data: