services:
  subscriber:
    build: .
    depends_on:
      db:
        condition: service_healthy # Wait until the 'db' service reports as healthy
    ports:
      - 8082:8088
    environment:
      - DBHOST=db
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otel.exotrend.live/v1/traces
      - OTEL_SERVICE_NAME=subscriber-micro-frontend
      - OTEL_RESOURCE_ATTRIBUTES=environment=docker,service.version=1.0.0
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - mysql_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # OpenTelemetry Collector for local development
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config-local.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Prometheus metrics
      - "8889:8889" # Prometheus exporter

  # Jaeger for local trace viewing
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger HTTP collector
      - "14250:14250" # Jaeger gRPC collector

volumes:
  mysql_db_data:
