- name: bootstrap mysql
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    compose_files:
      - mysql-adminer.yml

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - mysql-client
          - python3-pip
        state: present

    - name: Install python connectors and app deps
      ansible.builtin.pip:
        name:
          - pymysql
          - mysql-connector-python
          - fastapi
          - uvicorn
          - pydantic

    - name: Compose up mysql/adminer
      community.docker.docker_compose_v2:
        project_src: .
        files: "{{ compose_files }}"
        state: present
        remove_orphans: true

    - name: Install nektos/act
      ansible.builtin.shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | bash
      args:
        creates: bin/act
